name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-20.04'
        python-version:
          - '3.8'
        arch:
          - 'x86_64'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install Dependencies 
      run: |
                apt-get -y install software-properties-common && add-apt-repository ppa:deadsnakes/ppa && apt-get -y update && \
                apt install -y python3.8-venv && python3.8 -m venv venv38 && source venv38/bin/activate && \
                python3.8 -m pip install --upgrade pip && \
                python3.8 --version && \
                uname -m && \
                apt-get install libpq-dev -y libxml2-dev -y libxslt1-dev -y python3-dev -y && \
                apt-get install gcc-aarch64-linux-gnu -y && \
                python3.8 -m pip install backports.zoneinfo && \
                python3.8 -m pip install --upgrade pip wheel setuptools tox && \
                pip install -r requirements.txt && \
                pip install -r requirements-development.txt && \
                requirements-development.txt && \
                pip uninstall pyspark && \
                pip install -U databricks-connect==9.1.12 &7 \
                databricks-connect test && \
                deactivate'
                
          
